### ISSUE TITLE
New release please

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/Products.Carousel#14]
Tags for 3.0 and 3.0.1 were made a month ago by @jladage but he does not have PyPI rights.
Meanwhile I have fixed the tests, Travis is green.

Can we have a new 3.0.2 release? Maybe official releases for 3.0 and 3.0.1 too, for completeness.
Or can I have PyPI rights, username 'maurits'?

Current PyPI owners are @davisagli and @miohtama (and jbaldivieso and yomatters but I don't see those aliases on github).

**Comment by davisagli** [comment]
@mauritsvanrees I added you as an owner. Thanks!

**Comment by mauritsvanrees** [comment]
Thanks.
I have released 3.0, 3.0.1, and 3.0.2.
